### PR TITLE
Feature JWT recipe

### PR DESCRIPTION
**Pull request by rameshpolishetti**
This PR adds a new recipe to showcase how to use JWS service.

### CODE REVIEW

**Comment by jeffreybozek** [comment]
@rameshpolishetti The recipe looks good to me. The only issue is that the JWT service code is in https://github.com/TIBCOSoftware/mashling/tree/feature-jwt-service and not in master yet for Mashling.

**Comment by jpark800** [comment]
@jeffreybozek When can we expect the JWT service code to be merged into master?

**Comment by jeffreybozek** [comment]
@jpark800 I can cherrypick it out of the performance tweaks and submit a separate PR by the end of the week I think.

**Comment by jeffreybozek** [comment]
Once the corresponding PR (https://github.com/TIBCOSoftware/mashling/pull/215) is approved and merged this should be good to go.

**Pull request merged**
