### PR TITLE
Added Kubernetes scenario

### PR DESCRIPTION
**Pull request by retgits**
Added a scenario to deploy Mashling apps to Kubernetes (including creating Docker images) and leverage the environment variables to be able to update the K8s deployment afterwards

### CODE REVIEW

**Comment by retgits** [comment]
The ci-cd check fails because
```
Cloning into 'mashling-cicd'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/TIBCOSoftware/mashling-cicd.git/'
```

**Comment by jpark800** [comment]
Suggesting a couple enhancements to the readme:

- A little more detail on using SwaggerFileAppOne, SwaggerFileAppTwo on TCI would help at the end of the Intermezzo section: "For example, in TCI, open Integration->APISpecs->Import to import the swagger file and then Test/Copy the Endpoints."

- It would be helpful to mention a couple of commands for a novice user: 
At the beginning of Kubernetes section=> "minikube start" to start a k8s cluster 
At the beginning of the Testing section=> "minikube ip" to get the cluster ip to use in "curl --request http://<K8s>:30061/hello/world"

**Comment by retgits** [comment]
@jpark800, thanks for the feedback! I've updated the readme quite a bit :)

**Comment by jpark800** [comment]
@retgits It looks great! How about slight updates to it like below?

# Running Mashling on Kubernetes
This recipe will walk you through creating a Docker image out of your Mashling gateway and have the gateway route a request to one of the applications that matches the condition. 

## Kubernetes
Right, and now back to Kubernetes! To run the gateway on K8s you need to create a `deployment` and a `service` (the latter exposes the Mashling app to the outside world). You can use the accompanying `kube-deployment` and `kube-service` files. If you do, change the variables for the Docker image and the URLs in `kube-deployment`. After that, execute:

**Comment by retgits** [comment]
Sure! (and done 😄  )

**Comment by jpark800** [comment]
The following update is needed in both README and kube-deployment.yml to make it work.
<URL1> => <URL1>/greeting/:id1
<URL2> => <URL2>/farewell/:id1

Also, update the curl command syntax below:
$ curl --request http://<K8s external IP>:30061/hello/world => 
$ curl http://<K8s external IP>:30061/hello/world

**Comment by retgits** [comment]
Good idea! I've added a bit more explanation where the `:id` comes from and where it is used

**Pull request merged**
